spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false
    username: root
    password: root
    initialization-mode: never
    
security:  
  signing-key: <signing-key>